import { Geist, Geist_Mono } from "next/font/google";
import { Mulish } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mulish = Mulish({
  subsets: ['latin'],
  variable: '--font-mulish',
});

export const metadata = {
  title: "Prueba Tecnica Bitnovo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen flex flex-col items-center w-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mulish.variable} antialiased w-full h-full items-center justify-center flex`}
      >
        {children}
      </body>
    </html>
  );
}
